---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    controllers:
      backend:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.5.12@sha256:251f814864b3ed17ea8740b89a00363c5f14a3ca3738644fdec622eea78d3305

            env:
              TZ: ${TIMEZONE}
              LIBVA_DRIVER_NAME: i965
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_LOG_LEVEL: debug
              OLLAMA_MODELS: /models

            securityContext:
              privileged: true

            resources:
              requests:
                memory: 8G
                cpu: 2000m
                gpu.intel.com/i915: "1"
              limits:
                memory: 16G
                gpu.intel.com/i915: "1"

        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: intel.feature.node.kubernetes.io/gpu
                        operator: In
                        values:
                          - "true"

          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"

    service:
      backend:
        controller: backend
        ports:
          http:
            port: &port 11434

    ingress:
      backend:
        className: internal
        hosts:
          - host: &host ollama.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: backend
                  port: *port

    persistence:
      data:
        existingClaim: ollama-data-pvc
        advancedMounts:
          backend:
            main:
              - path: /.ollama

      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp

      models:
        type: nfs
        server: ${NAS_IP}
        path: /volume2/piNFS01/flux-cluster/ollama/models
        globalMounts:
          - path: /models
