---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: unifi-dest
  namespace: home
spec:
  trigger:
    manual: restore-once
  restic:
    repository: unifi-restic-secret
    copyMethod: Direct
    destinationPVC: unifi-config
    storageClassName: local-hostpath
