---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual-budget-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      actual-budget-exporter:
        strategy: RollingUpdate
        pod:
          annotations:
            secret.reloader.stakater.com/reload: actual-budget-exporter-config

        containers:
          app:
            image:
              repository: docker.io/sakowicz/actual-budget-prometheus-exporter
              tag: 1.1.7@sha256:5c76d2471594611395ab6b6521df5669d7138aa98745db3dccd6bc41e0e0464c
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: actual-budget-exporter-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      metrics:
        controller: *app
        ports:
          metrics:
            port: 3001
