---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        FRIGATE_MQTT_USERNAME: "{{ .FRIGATE_MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .FRIGATE_MQTT_PASSWORD }}"
        FRIGATE_RTSP_USER: "{{ .FRIGATE_RTSP_USER }}"
        FRIGATE_RTSP_PASSWORD: "{{ .FRIGATE_RTSP_PASSWORD}}"
        FRIGATE_RTSP_USER_WYZE3: "{{ .FRIGATE_RTSP_USER_WYZE3 }}"
        FRIGATE_RTSP_PASSWORD_WYZE3: "{{ .FRIGATE_RTSP_PASSWORD_WYZE3}}"
  dataFrom:
    - extract:
        key: frigate
