---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: false
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - database
          - default
          - finance
          - gameserver
          - home
          - media
          - monitoring
          - networking
#          - rook-ceph
          - security
          - storage
      name: "Turtle"
      customApps:
        - group: Home
          apps:
            - name: pfsense
              url: http://192.168.10.1
              icon: wall-fire
            - name: Synology
              url: http://192.168.10.15:5000
              icon: nas
            - name: S3400-48T6SP
              url: http://192.168.10.3
              icon: switch
            - name: T1500G-10MPS
              url: http://192.168.10.20
              icon: switch
            - name: S3700-24T4F
              url: http://192.168.10.2
              icon: switch
            - name: Rook Internal
              url: https://192.168.10.102:8443/
              icon: mdi:chess-rook
            - name: Grafana-DS
              url: https://grafana.davidstewen.com
              icon: simple-icons:grafana
#            - name: Gitops
#              url: https://gitops.davidstewen.com/
#              icon: sawtooth-wave
            - name: Minio
              url: http://192.168.10.198:9001/
              icon: simple-icons:minio
            - name: Home-Assistant-Pi4
              url: http://192.168.10.22:8123/
              icon: simple-icons:homeassistant
            - name: Home-Assistant-CM4
              url: http://192.168.10.84:8123/
              icon: simple-icons:homeassistant
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
    nodeSelector:
      node-role.kubernetes.io/worker: worker
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
