---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openspeedtest
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:

#    defaultPodOptions:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/arch
#                operator: In
#                values:
#                - arm64
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 50
#            preference:
#              matchExpressions:
#              - key: node-role.kubernetes.io/worker
#                operator: In
#                values:
#                - worker

    controllers:
      openspeedtest:
        containers:
          app:
            image:
              repository: openspeedtest/latest
              tag: v2.0.6
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1024Mi

    service:
      app:
        controller: openspeedtest
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/instance: "admin"
          hajimari.io/icon: "simple-icons:speedtest"
          hajimari.io/appName: "OpenSpeedTest"
          hajimari.io/group: "Networking"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Networking
          gethomepage.dev/name: openspeedtest
          gethomepage.dev/icon: mdi-resistor
          gethomepage.dev/description: OpenSpeedTest

        hosts:
          - host: openspeedtest.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
