---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/buroa/irqbalance
              tag: 1.9.4@sha256:1ae0230786206ea35e6ee3f9d170b0b47e15ecfb0c001af8d2744a312a4432fc
            env:
              IRQBALANCE_BANNED_CPULIST: 12-19 # 12-19 are E-cores
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      hostIPC: true
      hostPID: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
