---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netdata
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: netdata-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NETDATA_CLAIM_TOKEN: "{{ .PARENT_TOKEN }}"
        NETDATA_CHILD_TOKEN: "{{ .CHILD_TOKEN }}"
        NETDATA_ROOMS: 604f8cb2-4b1c-4249-9d4c-604325ad33c5
        NETDATA_CHILD_ROOMS: 604f8cb2-4b1c-4249-9d4c-604325ad33c5
  dataFrom:
    - extract:
        key: netdata
