---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter-amd64
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/joryirving/smartctl_exporter
      tag: 0.13.0@sha256:eaab31ca30d5859dd964f4b5a9d510351c5c50535cd3bb5852511fac04a08e65
    config:
      devices:
        - /dev/nvme0n1
        - /dev/nvme1n1
    nodeSelector:
      kubernetes.io/arch: amd64
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false

    resources:
      limits:
        memory: 64M
      requests:
        cpu: 10m
        memory: 32M
