---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../flux/components/common
resources:
  # Flux-Kustomizations
  - ./it-tools/ks.yaml
#  - ./searxng/ks.yaml
