apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5zsQuamqCfeTl7iMbRlS,iv:b8GBDTcwzqXwWKlLQyBwG7V+wve7pJbMjE7L+BcoBKE=,tag:gp33MDIxQRjzLX5Jz6DtYQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AennjR5xP+V0kNoIj0rykiKhFKhhO93a1h0LuzZbHfEWhrz2,iv:S7gr8GR1rBo3N3NMIFeMU70GYmGOdqdrbRl2sLz3t3M=,tag:A7FcJdMRklbDiyEuu9y9BA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gypmk3w2n4tmmwhkf22fdqmdjuglh73kxr7tp4a76euh00pxr9uqyzvsxu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVWZQQ3BZSWhDaUdTK1BQ
        WXZKU1dzR2czN0o2K3J0TTgwWGJNTTZLWFFJCmNJcTFwbnZ1WHpvV3lGNjRrQzJD
        YVgyQmlzVWVaKzN2UmRuKzJ6b0Nwa2cKLS0tIGVvVEZFbkpzOW5OVmtKNk9LSWJG
        V0taVkpMbEg3cHFxaWRFdUZsR1RpMzQK7mi1abdy7iB4CC0Eu/jhqlv7oEyN4aJW
        iMCvrAhq3RyybnIVQP1uzBpN1FyG0ttoyGfOVRZflxe0EU1Mpv68Sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-11T12:06:25Z"
  mac: ENC[AES256_GCM,data:yJ4YvWKVfm60M+MoWqDKTeGW0XqjNB3grNT/5/JzkuTYUUNO8XLy9K9S3U9TiBWC0PUpvMxOHO6BnbEJJT4RAgHTS4X48+qcXQAaVnSvKz03d96PPzxO/OfirwoyKoJuNlSsEaJZ5raPwew3CWNdx1XCr6ynwVS8rlDymhdssSk=,iv:bHwu8OQhbOgAlS5waJNgJ5oiNGy9SyVbhCtHwBqoT0E=,tag:+Asdi1zr08HnArDnQPXdjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
