---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-red
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
#    - name: volsync
#    - name: rook-ceph-cluster
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/home/node-red/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#  postBuild:
#    substitute:
#      APP: *app
#      VOLSYNC_CAPACITY: 5Gi
