---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy-system
components:
  - ../../flux/components/common
resources:
  # Flux-Kustomizations
  - ./trivy-operator/ks.yaml
