---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Authentik Auth
        OAUTH_CLIENT_ID: "{{ .OPENWEBUI_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPENWEBUI_OAUTH_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: "{{ .OPENWEBUI_OPENID_PROVIDER_URL }}"
        OPENID_REDIRECT_URI: "{{ .OPENWEBUI_OPENID_REDIRECT_URI }}"
  dataFrom:
    - extract:
        key: open-webui
