---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      version: 2.29.1
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64

    monitoring:
      podMonitor:
        enabled: false
      sidecar:
        enabled: true
        image:
          pullPolicy: "IfNotPresent"
          repository: "ekofr/pihole-exporter"
          tag: "v1.0.1"
          port: 9617
        resources:
          limits:
            memory: "128Mi"
    doh:
      enabled: false
      name: "cloudflared"
      repository: "crazymax/cloudflared"
      tag: "2021.5.7"
    serviceDhcp:
      enabled: false
    serviceDns:
      type: LoadBalancer
#      externalTrafficPolicy: Local
#      loadBalancerIP: ${SVC_PIHOLE_IP}
      annotations:
        lbipam.cilium.io/ips: 192.168.10.196
    serviceWeb:
      type: LoadBalancer
#      externalTrafficPolicy: Local
#      loadBalancerIP: ${SVC_PIHOLE_IP}
      annotations:
        lbipam.cilium.io/ips: 192.168.10.196
    virtualHost: "piholek.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: internal
#      annotations:
#        kubernetes.io/tls-acme: "true"
#        cert-manager.io/cluster-issuer: letsencrypt-prod
#        nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
#        nginx.ingress.kubernetes.io/auth-url: "http://authelia.kube-system.svc.cluster.local/api/authz/auth-request"
      path: /
      hosts:
        - &host "piholek.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    persistentVolumeClaim:
      enabled: true
#    tolerations:
#      - key: "arm"
#        operator: "Exists"
    replicaCount: 1
#    topologySpreadConstraints:
#      - maxSkew: 1
#        topologyKey: kubernetes.io/arch
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            release: pihole
#      - maxSkew: 1
#        topologyKey: kubernetes.io/hostname
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            release: pihole
#    adminPassword: ${PIHOLE_PASSWORD}
    extraEnvVars:
      RATE_LIMIT: "0/0"
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
      - 127.0.0.1
      - 1.1.1.1
